apiVersion: v1
kind: Service
metadata:
  name: reactbdarija-api-svc
  labels:
    app: reactbdarija
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3030
      targetPort: 3030
  selector:
    app: reactbdarija
    tier: api